name: gift_grab_client
description: A game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.7.1+48

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc_error_handler:   ^0.0.4
  collection: ^1.17.0
  cupertino_icons: ^1.0.2 
  flutter_app_info: ^3.0.3
  # gift_grab_ui:
  #   git: https://github.com/trey-a-hope/gift_grab_ui.git
  gift_grab_ui:
    path: /Users/treyhope/Desktop/Development/gift_grab_ui
  gift_grab_game:
    path: /Users/treyhope/Desktop/Development/gift_grab_game
  modal_util: ^0.0.2 
  nakama: ^1.3.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_login: ^5.1.0
  go_router: ^16.0.0
  flutter_bloc: ^9.1.1
  google_sign_in: ^7.1.1
  font_awesome_flutter: ^10.8.0
  sign_in_with_apple: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - .env 
    - shorebird.yaml
    
