name: gift_grab_client
description: A game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 25.8.11+59

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_search_bar: ^2.8.0
  bloc_error_handler: ^0.0.4
  bloc_test: ^10.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_login: ^5.1.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.9.0
  formz: ^0.8.0
  gap: ^3.0.1
  gift_grab_game:
    git: https://github.com/trey-a-hope/gift_grab_game.git
  gift_grab_ui:
    git: https://github.com/trey-a-hope/gift_grab_ui.git
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  logger: ^2.6.1
  material_design_icons_flutter: ^7.0.7296
  modal_util: ^0.0.7
  mocktail: ^1.0.4
  nakama: ^1.3.0
  package_info_plus: ^8.3.1
  settings_ui: ^2.0.2
  sign_in_with_apple: ^7.0.1
  universal_platform: ^1.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - .env 
    - shorebird.yaml