name: gift_grab_client
description: A game made using Flame where users grab presents to increase their scores.
publish_to: "none"
version: 1.7.1+48

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  gift_grab_ui:
    # path: /Users/treyhope/Desktop/Development/gift_grab_ui
    git: https://github.com/trey-a-hope/gift_grab_ui.git
  gift_grab_game:
    path: /Users/treyhope/Desktop/Development/gift_grab_game
  window_manager: ^0.5.1
    # git: https://github.com/trey-a-hope/gift_grab_game.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - .env 
    - shorebird.yaml
    
